version: '3.8'
services:
  media-server:
    image: bluenviron/mediamtx:latest
    container_name: rtsp-server
    restart: unless-stopped
    ports:
      - "8554:8554" # Порт для RTSP (TCP/UDP)
      - "1935:1935" # Порт для RTMP (если нужно)
      - "8888:8888" # Порт для HLS (просмотр в браузере)
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTC=no